require_relative 'piece'
require_relative 'sliding_piece/bishop'
require_relative 'stepping_piece/knight'
require_relative 'pawn'
require_relative 'stepping_piece/king'
require_relative 'null_piece'
require_relative 'sliding_piece/rook'
require_relative 'sliding_piece/queen'
